### ISSUE TITLE
[Question] wall clock time for training a `mt80` offline model

### ISSUE THREAD

**Issue by bkkgbkjb** [nicklashansen/tdmpc2#41]
Hi all,

thanks for such an elegant and performant algorithm!

I wanna know how long it takes for you to perform a from-scratch `mt80` offline training using current code?
in the original paper, it's reported on a single `Nvidia 3090` , only ~ 5days are needed for a `19M` model

But in my case, I train a `19M` model on both A100-80G and A100-40G, both of them need more than 90days

I wonder anybody has trained a full `mt80` offline model?  
Is there anything I need to change in hyperparamters? (I noticed the `training steps` are `10M` which seems quite large for a model-based algorithm)

Huge thanks in advance, please help me 

BTW,
my running command is: `python tdmpc2/train.py task=mt80 model_size=19 batch_size=1024 data_dir=${DIR}/dataset/mt80/ save_csv=False`  
dependencies are installed in docker

extracted `hydra` config is as follows:  
```yaml
task: mt80
obs: state
checkpoint: ???
eval_episodes: 10
eval_freq: 500000
steps: 10000000
batch_size: 1024
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 0.0003
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1000000
exp_name: default
data_dir: ${DIR}/projs/tdmpc2/optim/dataset/mt80/
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5
log_std_min: -10
log_std_max: 2
entropy_coef: 0.0001
num_bins: 101
vmin: -10
vmax: 10
model_size: 19
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8
wandb_project: ???
wandb_entity: ???
wandb_silent: false
disable_wandb: true
save_csv: false
save_video: false
save_agent: true
seed: 11111
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
```
